#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6F5447F95D001D85 (ossi@kde.org)
#
Name     : isync
Version  : 1.3.4
Release  : 3
URL      : https://sourceforge.net/projects/isync/files/isync/1.3.4/isync-1.3.4.tar.gz
Source0  : https://sourceforge.net/projects/isync/files/isync/1.3.4/isync-1.3.4.tar.gz
Source1  : https://sourceforge.net/projects/isync/files/isync/1.3.4/isync-1.3.4.tar.gz.asc
Summary  : Utility to synchronize IMAP mailboxes with local maildir folders
Group    : Development/Tools
License  : GPL-2.0
Requires: isync-bin = %{version}-%{release}
Requires: isync-license = %{version}-%{release}
Requires: isync-man = %{version}-%{release}
BuildRequires : cyrus-sasl-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(zlib)

%description
isync is a command line utility which synchronizes mailboxes; currently
Maildir and IMAP4 mailboxes are supported.
New messages, message deletions and flag changes can be propagated both ways.
It is useful for working in disconnected mode, such as on a laptop or with a
non-permanent internet collection (dIMAP).

%package bin
Summary: bin components for the isync package.
Group: Binaries
Requires: isync-license = %{version}-%{release}

%description bin
bin components for the isync package.


%package doc
Summary: doc components for the isync package.
Group: Documentation
Requires: isync-man = %{version}-%{release}

%description doc
doc components for the isync package.


%package license
Summary: license components for the isync package.
Group: Default

%description license
license components for the isync package.


%package man
Summary: man components for the isync package.
Group: Default

%description man
man components for the isync package.


%prep
%setup -q -n isync-1.3.4
cd %{_builddir}/isync-1.3.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612383227
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1612383227
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/isync
cp %{_builddir}/isync-1.3.4/COPYING %{buildroot}/usr/share/package-licenses/isync/dfac199a7539a404407098a2541b9482279f690d
cp %{_builddir}/isync-1.3.4/debian/copyright %{buildroot}/usr/share/package-licenses/isync/6743e7ed1deaa4517560058bb285d70c11eb58c4
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mbsync
/usr/bin/mbsync-get-cert

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/isync/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/isync/6743e7ed1deaa4517560058bb285d70c11eb58c4
/usr/share/package-licenses/isync/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mbsync.1
